CONFIG_USBD_CDC_ACM_LOG_LEVEL_OFF=y

CONFIG_USB_DEVICE_STACK_NEXT=y

CONFIG_SERIAL=y
CONFIG_UART_LINE_CTRL=y
CONFIG_UART_USE_RUNTIME_CONFIGURE=y
CONFIG_CDC_ACM_SERIAL_INITIALIZE_AT_BOOT=n

CONFIG_SAMPLE_USBD_PID=0x0001
CONFIG_SAMPLE_USBD_PRODUCT="USBD CDC ACM bridge sample"

CONFIG_WIFI_ST67W611M1=n
CONFIG_USBD_CDC_ACM_BUF_POOL_SIZE=4096
CONFIG_UART_BRIDGE_BUF_SIZE=4096
